// VisualMenu Studio - Universal Exporter Engine v6 (Vision 2026)
window.UniversalExporter = {
    templates: {
        minecraft_neoforge: (ws) => {
            const textures = ws.filter(w => w.texture && !w.texture.startsWith('http'));
            let constants = textures.map(w => `    private static final ResourceLocation ${w.id.toUpperCase()}_TEX = ResourceLocation.fromNamespaceAndPath("modid", "${w.texture.split(':').pop()}");`).join('\n');
            return `import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.gui.GuiGraphics;

public class MyScreen extends Screen {
${constants}

    @Override
    public void render(GuiGraphics g, int mx, int my, float pt) {
        super.render(g, mx, my, pt);
        ${ws.map(w => {
            const x = `this.width / 2 + (${w.x} - 960)`, y = `this.height / 2 + (${w.y} - 540)`;
            if (w.texture && !w.texture.startsWith('http')) return `g.blit(${w.id.toUpperCase()}_TEX, ${x}, ${y}, ${w.u}, ${w.v}, ${w.width}, ${w.height}, ${w.uw}, ${w.uh});`;
            if (w.type === 'label') return `g.drawString(this.font, "${w.text}", ${x}, ${y}, 0xFFFFFF);`;
            return "";
        }).filter(c => c).join('\n        ')}
    }
}`;
        },
        godot_gdscript: (ws) => `extends Control
# Generated by VisualMenu Studio

func _ready():
    ${ws.map(w => {
        const x = w.x, y = w.y;
        if (w.texture) return `# Load texture for ${w.id}\n    var tex_${w.id} = load("${w.texture}")\n    # Add Sprite/TextureRect logic here`;
        return `var label_${w.id} = Label.new()\n    label_${w.id}.text = "${w.text || ''}"\n    label_${w.id}.position = Vector2(${x}, ${y})\n    add_child(label_${w.id})`;
    }).join('\n    ')}

func _draw():
    ${ws.map(w => {
        if (!w.texture) return "";
        return `draw_texture_rect_region(load("${w.texture}"), Rect2(${w.x}, ${w.y}, ${w.width}, ${w.height}), Rect2(${w.u}, ${w.v}, ${w.width}, ${w.height}))`;
    }).filter(c => c).join('\n    ')}`,

        unity_csharp: (ws) => `using UnityEngine;
using UnityEngine.UIElements;

public class MyUIDocument : MonoBehaviour {
    void OnEnable() {
        var root = GetComponent<UIDocument>().rootVisualElement;
        ${ws.map(w => {
            return `var el_${w.id} = new VisualElement();\n        el_${w.id}.style.left = ${w.x}f;\n        el_${w.id}.style.top = ${w.y}f;\n        el_${w.id}.style.width = ${w.width}f;\n        el_${w.id}.style.height = ${w.height}f;\n        root.Add(el_${w.id});`;
        }).join('\n        ')}
    }
}`,

        tailwind_web: (ws) => `<div class="relative w-[1920px] h-[1080px] bg-slate-900 overflow-hidden">
    ${ws.map(w => {
        let style = `left: ${w.x}px; top: ${w.y}px; width: ${w.width}px; height: ${w.height}px;`;
        if (w.texture) style += ` background-image: url('${w.texture}'); background-position: -${w.u}px -${w.v}px;`;
        return `<div id="${w.id}" class="absolute" style="${style}">
        ${w.text ? `<span class="text-white">${w.text}</span>` : ''}
    </div>`;
    }).join('\n    ')}
</div>`
    },

    generate(widgets, platform, loader, format) {
        if (format === 'json') return { code: JSON.stringify(widgets, null, 4), meta: "Project JSON" };
        if (format === 'css') return { code: this.generateCSS(widgets), meta: "Layout CSS" };

        const key = `${platform}_${loader}`;
        const template = this.templates[key] || this.templates[platform] || (() => "// No template available");
        const code = template(widgets);
        
        return { code: this.highlight(code, platform), meta: `${platform.toUpperCase()} (${loader})` };
    },

    generateCSS(ws) {
        return ws.map(w => `#${w.id} { position: absolute; left: ${w.x}px; top: ${w.y}px; width: ${w.width}px; height: ${w.height}px; ${w.texture ? `background-image: url('${w.texture}'); background-position: -${w.u}px -${w.v}px;` : ''} }`).join('\n');
    },

    highlight(code, platform) {
        const keywords = {
            minecraft: ['public', 'class', 'extends', 'protected', 'void', 'super', 'this', 'new', 'import', 'return', 'static', 'final', 'private'],
            godot: ['extends', 'func', 'var', 'load', 'add_child', 'Vector2', 'Rect2'],
            unity: ['using', 'public', 'class', 'void', 'GetComponent', 'new', 'var'],
            python: ['import', 'def', 'class', 'for', 'if', 'while', 'as', 'True', 'False'],
            c_cpp: ['int', 'void', 'include', 'while', 'return', 'main', 'if']
        };
        let h = code.replace(/(\".*?\")/g, '<span style="color: #6a8759;">$1</span>');
        (keywords[platform] || []).forEach(kw => h = h.replace(new RegExp(`\\b${kw}\\b`, 'g'), `<span style="color: #cc7832;">${kw}</span>`));
        return h.replace(/(\/\/.*|#.*)/g, '<span style="color: #808080;">$1</span>');
    }
};

window.addScreen = () => window.addScreen && window.addScreen(); // Proxy for app.js

// Clipboard
document.getElementById('copyCode').addEventListener('click', () => {
    navigator.clipboard.writeText(document.getElementById('codeOutput').innerText).then(() => {
        const btn = document.getElementById('copyCode');
        btn.innerHTML = '<i class="fas fa-check"></i>';
        setTimeout(() => btn.innerHTML = '<i class="far fa-copy"></i>', 2000);
    });
});
