// VisualMenu Studio - Universal Exporter Engine v7 (Bug-Fixed)
window.UniversalExporter = {
    templates: {
        minecraft_neoforge: (ws) => {
            const textures = ws.filter(w => w.texture && !w.texture.startsWith('http'));
            let constants = textures.map(w =>
                `    private static final ResourceLocation ${w.id.toUpperCase()}_TEX = ResourceLocation.fromNamespaceAndPath("modid", "${w.texture.split(':').pop()}");`
            ).join('\n');
            const body = ws.map(w => {
                const x = `this.width / 2 + (${w.x} - 960)`;
                const y = `this.height / 2 + (${w.y} - 540)`;
                if (w.texture && !w.texture.startsWith('http'))
                    return `g.blit(${w.id.toUpperCase()}_TEX, ${x}, ${y}, ${w.u}, ${w.v}, ${w.width}, ${w.height}, ${w.uw}, ${w.uh});`;
                if (w.type === 'label') return `g.drawString(this.font, "${w.text}", ${x}, ${y}, 0xFFFFFF);`;
                if (w.type === 'button') return `this.addRenderableWidget(Button.builder(Component.literal("${w.text}"), btn -> {}).bounds(${x}, ${y}, ${w.width}, ${w.height}).build());`;
                if (w.type.includes('bar')) return `// Progress bar: ${w.id} (x=${w.x}, y=${w.y}, w=${w.width}, h=${w.height}, progress=${w.progress}%)`;
                return '';
            }).filter(Boolean).join('\n        ');
            return `import net.minecraft.resources.ResourceLocation;\nimport net.minecraft.client.gui.GuiGraphics;\nimport net.minecraft.client.gui.screens.Screen;\nimport net.minecraft.network.chat.Component;\n\npublic class ${ws[0] ? 'MyScreen' : 'EmptyScreen'} extends Screen {\n${constants}\n\n    protected ${ws[0] ? 'MyScreen' : 'EmptyScreen'}() {\n        super(Component.literal("My Screen"));\n    }\n\n    @Override\n    public void render(GuiGraphics g, int mx, int my, float pt) {\n        this.renderBackground(g, mx, my, pt);\n        super.render(g, mx, my, pt);\n        ${body}\n    }\n}`;
        },

        minecraft_forge: (ws) => {
            const body = ws.map(w => {
                const x = `this.width / 2 + (${w.x} - 960)`;
                const y = `this.height / 2 + (${w.y} - 540)`;
                if (w.type === 'label') return `guiGraphics.drawString(this.font, "${w.text}", ${x}, ${y}, 0xFFFFFF, false);`;
                if (w.type.includes('bar')) return `// Bar: ${w.id} at (${w.x},${w.y}) ${w.progress}%`;
                return '';
            }).filter(Boolean).join('\n        ');
            return `// Forge 1.20.1 Screen\nimport net.minecraft.client.gui.GuiGraphics;\nimport net.minecraft.client.gui.screens.Screen;\nimport net.minecraft.network.chat.Component;\n\npublic class MyScreen extends Screen {\n    protected MyScreen() { super(Component.literal("My Screen")); }\n\n    @Override\n    public void render(GuiGraphics guiGraphics, int pMouseX, int pMouseY, float pPartialTick) {\n        this.renderBackground(guiGraphics);\n        super.render(guiGraphics, pMouseX, pMouseY, pPartialTick);\n        ${body}\n    }\n}`;
        },

        minecraft_fabric: (ws) => {
            const body = ws.map(w => {
                if (w.type === 'label') return `context.drawText(textRenderer, "${w.text}", ${w.x}, ${w.y}, 0xFFFFFF, false);`;
                return '';
            }).filter(Boolean).join('\n        ');
            return `// Fabric 1.20.1 Screen\nimport net.minecraft.client.gui.DrawContext;\nimport net.minecraft.client.gui.screen.Screen;\nimport net.minecraft.text.Text;\n\npublic class MyScreen extends Screen {\n    public MyScreen() { super(Text.literal("My Screen")); }\n\n    @Override\n    public void render(DrawContext context, int mouseX, int mouseY, float delta) {\n        super.render(context, mouseX, mouseY, delta);\n        ${body}\n    }\n}`;
        },

        godot_gdscript: (ws) => {
            const ready = ws.map(w => {
                if (w.texture) return `# Texture: ${w.id}\n\tvar ${w.id} = TextureRect.new()\n\t${w.id}.texture = load("${w.texture}")\n\t${w.id}.position = Vector2(${w.x}, ${w.y})\n\t${w.id}.size = Vector2(${w.width}, ${w.height})\n\tadd_child(${w.id})`;
                if (w.type === 'label') return `var ${w.id} = Label.new()\n\t${w.id}.text = "${w.text || ''}"\n\t${w.id}.position = Vector2(${w.x}, ${w.y})\n\tadd_child(${w.id})`;
                if (w.type === 'button') return `var ${w.id} = Button.new()\n\t${w.id}.text = "${w.text || 'Button'}"\n\t${w.id}.position = Vector2(${w.x}, ${w.y})\n\t${w.id}.size = Vector2(${w.width}, ${w.height})\n\tadd_child(${w.id})`;
                if (w.type.includes('bar')) return `var ${w.id} = ProgressBar.new()\n\t${w.id}.position = Vector2(${w.x}, ${w.y})\n\t${w.id}.size = Vector2(${w.width}, ${w.height})\n\t${w.id}.value = ${w.progress}\n\tadd_child(${w.id})`;
                return `# Widget: ${w.id} (type: ${w.type})`;
            }).join('\n\t');
            return `extends Control\n# Generated by VisualMenu Studio\n\nfunc _ready():\n\t${ready}`;
        },

        unity_csharp: (ws) => {
            const body = ws.map(w =>
                `var el_${w.id} = new VisualElement();\n        el_${w.id}.style.left = ${w.x}f;\n        el_${w.id}.style.top = ${w.y}f;\n        el_${w.id}.style.width = ${w.width}f;\n        el_${w.id}.style.height = ${w.height}f;${w.text ? `\n        el_${w.id}.Add(new Label("${w.text}"));` : ''}\n        root.Add(el_${w.id});`
            ).join('\n        ');
            return `using UnityEngine;\nusing UnityEngine.UIElements;\n\npublic class MyUIDocument : MonoBehaviour {\n    void OnEnable() {\n        var root = GetComponent<UIDocument>().rootVisualElement;\n        ${body}\n    }\n}`;
        },

        python_tkinter: (ws) => {
            const body = ws.map(w => {
                if (w.type === 'label') return `tk.Label(root, text="${w.text || ''}").place(x=${w.x}, y=${w.y})`;
                if (w.type === 'button') return `tk.Button(root, text="${w.text || 'Button'}").place(x=${w.x}, y=${w.y}, width=${w.width}, height=${w.height})`;
                if (w.type.includes('bar')) return `# Progress bar at (${w.x}, ${w.y}): use ttk.Progressbar`;
                return `# Widget ${w.id} (${w.type}) at (${w.x}, ${w.y})`;
            }).join('\n');
            return `import tkinter as tk\nfrom tkinter import ttk\n\nroot = tk.Tk()\nroot.title("My App")\nroot.geometry("${ws[0] ? '1920x1080' : '800x600'}")\n\n${body}\n\nroot.mainloop()`;
        },

        python_pygame: (ws) => {
            const body = ws.map(w => {
                const colorHex = w.color ? `(${parseInt(w.color.slice(1,3),16)}, ${parseInt(w.color.slice(3,5),16)}, ${parseInt(w.color.slice(5,7),16)})` : '(0, 255, 136)';
                if (w.type === 'label') return `screen.blit(font.render("${w.text || ''}", True, ${colorHex}), (${w.x}, ${w.y}))`;
                if (w.type === 'button') return `pygame.draw.rect(screen, ${colorHex}, (${w.x}, ${w.y}, ${w.width}, ${w.height}))`;
                if (w.type.includes('bar')) return `pygame.draw.rect(screen, ${colorHex}, (${w.x}, ${w.y}, int(${w.width} * ${w.progress}/100), ${w.height}))`;
                return `# Widget: ${w.id}`;
            }).join('\n    ');
            return `import pygame\npygame.init()\nscreen = pygame.display.set_mode((1920, 1080))\nfont = pygame.font.SysFont("Arial", 20)\nclock = pygame.time.Clock()\n\nrunning = True\nwhile running:\n    for event in pygame.event.get():\n        if event.type == pygame.QUIT:\n            running = False\n    screen.fill((18, 20, 26))\n    ${body}\n    pygame.display.flip()\n    clock.tick(60)\n\npygame.quit()`;
        },

        c_cpp_raylib: (ws) => {
            const body = ws.map(w => {
                const [r, g, b] = w.color ? [parseInt(w.color.slice(1,3),16), parseInt(w.color.slice(3,5),16), parseInt(w.color.slice(5,7),16)] : [0, 255, 136];
                if (w.type === 'label') return `DrawText("${w.text || ''}", ${w.x}, ${w.y}, 20, (Color){${r}, ${g}, ${b}, 255});`;
                if (w.type === 'button') return `DrawRectangle(${w.x}, ${w.y}, ${w.width}, ${w.height}, (Color){${r}, ${g}, ${b}, 200});\nDrawText("${w.text || ''}", ${w.x}+5, ${w.y}+5, 16, WHITE);`;
                if (w.type.includes('bar')) return `DrawRectangle(${w.x}, ${w.y}, ${w.width}, ${w.height}, DARKGRAY);\nDrawRectangle(${w.x}, ${w.y}, (int)(${w.width} * ${w.progress}/100.0f), ${w.height}, (Color){${r}, ${g}, ${b}, 255});`;
                return `// Widget: ${w.id}`;
            }).join('\n    ');
            return `#include "raylib.h"\n\nint main(void) {\n    InitWindow(1920, 1080, "My Game HUD");\n    SetTargetFPS(60);\n\n    while (!WindowShouldClose()) {\n        BeginDrawing();\n        ClearBackground((Color){12, 14, 20, 255});\n        ${body}\n        EndDrawing();\n    }\n\n    CloseWindow();\n    return 0;\n}`;
        }
    },

    generate(widgets, platform, loader, format) {
        if (format === 'json') return { code: this.escapeHtml(JSON.stringify(widgets, null, 4)), meta: "Project JSON" };
        if (format === 'css') return { code: this.escapeHtml(this.generateCSS(widgets)), meta: "Layout CSS" };

        const key = `${platform}_${loader}`;
        const template = this.templates[key] || this.templates[platform] || (() => "// No template available for this platform/loader combination.");
        let code;
        try {
            code = template(widgets);
        } catch (err) {
            code = `// Error generating code: ${err.message}`;
        }
        return { code: this.highlight(code, platform), meta: `${platform.toUpperCase()} · ${loader}` };
    },

    generateCSS(ws) {
        return ws.map(w =>
            `#${w.id} {\n  position: absolute;\n  left: ${w.x}px;\n  top: ${w.y}px;\n  width: ${w.width}px;\n  height: ${w.height}px;${w.color ? `\n  color: ${w.color};` : ''}${w.texture ? `\n  background-image: url('${w.texture}');\n  background-position: -${w.u}px -${w.v}px;` : ''}\n}`
        ).join('\n\n');
    },

    // FIX #10: Use escapeHtml first, then highlight — so copying gives clean text
    // FIX #11: Highlight does NOT re-process already-wrapped spans
    escapeHtml(code) {
        return code
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
    },

    highlight(rawCode, platform) {
        const escaped = this.escapeHtml(rawCode);
        const keywords = {
            minecraft: ['public', 'class', 'extends', 'protected', 'void', 'super', 'this', 'new', 'import', 'return', 'static', 'final', 'private', 'int', 'boolean', 'float'],
            godot: ['extends', 'func', 'var', 'load', 'add_child', 'Vector2', 'Rect2', 'true', 'false', 'null'],
            unity: ['using', 'public', 'class', 'void', 'GetComponent', 'new', 'var', 'private', 'float', 'int'],
            python: ['import', 'from', 'def', 'class', 'for', 'if', 'while', 'as', 'True', 'False', 'None', 'return', 'in'],
            c_cpp: ['int', 'void', 'include', 'while', 'return', 'main', 'if', 'float', 'const', 'struct']
        };
        // Process in order: strings → keywords → comments
        let h = escaped.replace(/(&quot;.*?&quot;)/g, '<span class="hl-str">$1</span>');
        (keywords[platform] || []).forEach(kw => {
            h = h.replace(new RegExp(`(?<![\\w\\-])${kw}(?![\\w\\-])`, 'g'), `<span class="hl-kw">${kw}</span>`);
        });
        h = h.replace(/(\/\/[^\n]*|#[^\n]*)/g, '<span class="hl-cmt">$1</span>');
        return `<code>${h}</code>`;
    }
};

// FIX #9: Remove the circular reference proxy
// window.addScreen is set directly in app.js

// FIX #10: copyCode copies plain text (.textContent), not HTML
document.getElementById('copyCode').addEventListener('click', () => {
    const codeEl = document.getElementById('codeOutput');
    // Get raw text without HTML tags
    const text = codeEl.textContent || codeEl.innerText;
    navigator.clipboard.writeText(text).then(() => {
        const btn = document.getElementById('copyCode');
        const original = btn.innerHTML;
        btn.innerHTML = '<i class="fas fa-check"></i> Copied!';
        setTimeout(() => btn.innerHTML = original, 2000);
    }).catch(() => {
        // Fallback for environments without clipboard API
        const ta = document.createElement('textarea');
        ta.value = text;
        document.body.appendChild(ta);
        ta.select();
        document.execCommand('copy');
        document.body.removeChild(ta);
    });
});
